openapi: 3.0.0
info:
  title: Token Prices API
  description: This API returns the latest token prices
  version: '0.1.0'
paths:
  /token-prices:
    get:
      summary: Get the latest token prices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  TON:
                    type: number
                  JUSDT:
                    type: number
                  JUSDC:
                    type: number
