openapi: 3.0.0
info:
  title: Swap Simulation API
  description: API to simulate swap transactions in a decentralized exchange.
  version: '1.0.0'
paths:
  /simulate-swap:
    get:
      summary: Simulate a swap
      parameters:
        - name: offerAddress
          in: query
          description: The blockchain address offering the swap.
          required: true
          schema:
            type: string
          example: EQDpKrPWD9olggJI9NAEt2b9WOxUYuspoQRCia0kQyO6EayJ
        - name: askAddress
          in: query
          description: The blockchain address asking for the swap.
          required: true
          schema:
            type: string
          example: EQDXPXpCRQScbFgRu_TXfAOHpKP6WmmOP1nICGq6ujaEKWsF
        - name: units
          in: query
          description: The number of units offered for the swap.
          required: true
          schema:
            type: integer
            minimum: 1
          example: 200
        - name: slippageTolerance
          in: query
          description: Maximum tolerated slippage in the transaction as a fraction of 1.
          required: true
          schema:
            type: number
            format: float
            minimum: 0
            maximum: 1
          example: 0.01
        - name: referralAddress
          in: query
          description: Optional referral blockchain address involved in the transaction.
          required: false
          schema:
            type: string
          example: UQAFFzJLx4ThDW5YqPbdG5nAfg8E7fzZDs2UDErDaljOLvYB
      responses:
        '200':
          description: Successful simulation of the swap.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: 'common.yaml#/components/schemas/SimulateSwapResult'
  /simulate-swap-reverse:
    get:
      summary: Simulate a reverse-swap
      parameters:
        - name: offerAddress
          in: query
          description: The blockchain address offering the swap.
          required: true
          schema:
            type: string
          example: EQDpKrPWD9olggJI9NAEt2b9WOxUYuspoQRCia0kQyO6EayJ
        - name: askAddress
          in: query
          description: The blockchain address asking for the swap.
          required: true
          schema:
            type: string
          example: EQDXPXpCRQScbFgRu_TXfAOHpKP6WmmOP1nICGq6ujaEKWsF
        - name: units
          in: query
          description: The number of units offered for the swap.
          required: true
          schema:
            type: integer
            minimum: 1
          example: 14774
        - name: slippageTolerance
          in: query
          description: Maximum tolerated slippage in the transaction as a fraction of 1.
          required: true
          schema:
            type: number
            format: float
            minimum: 0
            maximum: 1
          example: 0.01
        - name: referralAddress
          in: query
          description: Optional referral blockchain address involved in the transaction.
          required: false
          schema:
            type: string
          example: UQAFFzJLx4ThDW5YqPbdG5nAfg8E7fzZDs2UDErDaljOLvYB
      responses:
        '200':
          description: Successful simulation of the swap.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: 'common.yaml#/components/schemas/SimulateSwapResult'
