openapi: 3.0.0

info:
  title: Tasks API
  description: This API returns the tasks data
  version: '0.1.0'

paths:
  /tasks/cpmm_beta:
    get:
      summary: Get the tasks data
      parameters:
        - in: query
          name: senderAddress
          required: true
          schema:
            type: string
          description: The address of the sender
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  convertContractAt:
                    type: string
                  earnContractAt:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  data:
                    type: array
                    items: {}

components:
  schemas:
    Task:
      type: object
      properties:
        convertContractAt:
          type: string
          description: Convert contract time
        earnContractAt:
          type: string
          description: Earn contract time
      required:
        - convertContractAt
        - earnContractAt
