openapi: 3.0.0
info:
  title: Token Prices API
  description: This API returns the latest token prices
  version: '0.1.0'
paths:
  /token-prices:
    get:
      summary: Get the latest token prices
      parameters:
        - name: tokenIds
          in: query
          description: Token ids to retrieve prices for.
          required: true
          schema:
            type: array
          example: ['id']

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'common.yaml#/components/schemas/Token'
  /token-prices-history:
    get:
      summary: Get all token prices of history
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'common.yaml#/components/schemas/Token'
