openapi: 3.0.0
info:
  title: Tokens API
  description: This API returns the latest tokens data
  version: '0.1.0'
paths:
  /tokens:
    get:
      summary: Get the latest tokens data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'common.yaml#/components/schemas/Token'
